#pragma once

#define SPAWN_INTERVAL 300
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define ASSERTS_DIR "assets/"
#define GAME_TITLE "Quick Side Scroller"
#define ASSETS_DIR "assets/"
#define ATLAS_JSON_FILE "qss.json"
#define ATLAS_PNG_FILE "qss.png"
#define MUSIC_FILE "music.ogg"
#define PLAYER_POS_X 50
#define PLAYER_POS_Y 200
#define PLAYER_POS_Z 10
#define PLAYER_TEXTURE "ship.png"
#define NUM_PARALLAX_LAYERS 5
#define BACKGROUND_0_TEXTURE "bg0.png"
#define BACKGROUND_0_POS_Y 0
#define BACKGROUND_1_TEXTURE "bg1.png"
#define BACKGROUND_1_POS_Y 284, 266, 366, 347
#define BACKGROUND_2_TEXTURE "bg2.png"
#define BACKGROUND_2_POS_Y 266
#define BACKGROUND_3_TEXTURE "bg3.png"
#define BACKGROUND_3_POS_Y 366
#define BACKGROUND_4_TEXTURE "fg.png"
#define BACKGROUND_4_POS_Y 347
#define PARALLAX_SPEED 30
#define SHOT_POS_X 0
#define SHOT_POS_Y 0
#define SHOT_POS_Z 9
#define SHOT_TEXTURE "shot.png"
#define EXPLOSION_POS_X 0
#define EXPLOSION_POS_Y 0
#define EXPLOSION_POS_Z 11
#define EXPLOSION_TEXTURE "explosion.png"
#define ENEMY_POS_X 0
#define ENEMY_POS_Y 0
#define ENEMY_POS_Z 8
#define ENEMY_TEXTURE "enemy.png"
#define SOUND_EXPLOSION_FILE "explosion.wav"
#define SOUND_LASER_FILE "laser.wav"
#define POOL_SIZE 10
#define NUM_ENEMIES 10
#define SPAWN_ENEMY_HEIGHT 350
#define SPAWN_ENEMY_PADDING 20
#define SCORE_POS_X 508
#define SCORE_POS_Y 10
#define SCORE_POS_Z 20
#define SCORE_TEXTURE "font.png"
#define ZOOM_X2 2.0F
#define ENEMY_WAVE_SEPARATION 120.0F
#define ENEMY_WAVE_AMPLITUDE 25.0F
#define ENEMY_LEFT_EDGE -64
#define ENEMY_HORIZONTAL_SPACE 64
#define HUNDRED_PERCENT 100.0F
#define NUM_POINTS 3
#define MAX_TEXTURE "max.png"
#define SCORE_FRAME_WIDTH 24
#define SCORE_FRAME_HEIGHT 27
#define SCORE_SPACE 4
#define SCORE_DIGITS 5
#define SCORE_PADDING 84